Capture stdout and stderr separately when calling Azure CLI (#460)
## Changes

They were captured together such that any warnings emitted to stderr
would turn the output of the command into malformed JSON and raise an
error.

Traces all the way back to #30.

## Tests

- [x] `make test` run locally
- [x] `make fmt` applied
- [ ] relevant integration tests applied

diff --git a/tests/testdata/az b/tests/testdata/az
--- a/tests/testdata/az
+++ b/tests/testdata/az
@@ -1,16 +1,20 @@
 #!/bin/bash
 
-if [ "yes" == "$FAIL" ]; then 
+if [ -n "$WARN" ]; then
+    >&2 /bin/echo "WARNING: ${WARN}"
+fi
+
+if [ "yes" == "$FAIL" ]; then
     >&2 /bin/echo "This is just a failing script."
     exit 1
 fi
 
-if [ "logout" == "$FAIL" ]; then 
+if [ "logout" == "$FAIL" ]; then
     >&2 /bin/echo "No subscription found. Run 'az account set' to select a subscription."
     exit 1
 fi
 
-if [ "corrupt" == "$FAIL" ]; then 
+if [ "corrupt" == "$FAIL" ]; then
     /bin/echo "{accessToken: ..corrupt"
     exit
 fi
